EVM/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('accounts.urls')),
    path('generator/', include('generator.urls')),
    path('admin/', admin.site.urls),
    #url(r'^image/', include('generator.urls')),
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

generator/urls.py
from django.conf.urls import include, url
from generator import views
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

app_name = 'generator'

urlpatterns = [
    path('', views.home, name="home"),
    path('Upload_Photo', views.Upload_Photo, name='Upload_Photo'),
    path('home', views.home, name='home'),
    path('create', views.create, name='create'),
    path('beforeImageCrop/', views.beforeImageCrop),
    path('show_problem', views.show_problem, name='show_problem'),
    path('createCropImage/', csrf_exempt(views.createCropImage)),
    path('ImageCrop/<word>/', views.ImageCrop),
    path('CropToOCR/', views.crop_to_OCR),
    path('show_UserProblem', views.show_UserProblem, name='show_UserProblem'),
    path('OneProblem/<word>/', views.show_OneProblem),
    path('solveProblem/<word>/', views.solve_Problem),
    path('showAnswer', views.show_Answer, name='showAnswer'),
    path('OneBlankNum/<word>/', views.show_OneBlankNum),
    path('ChangeBlankNum/<word>', views.change_BlankNum, name='ChangeBlankNum'),
    path('show_UserBlankNum', views.show_UserBlankNum, name='show_UserBlankNum'),
    path('show_DeveloperInfo', views.show_DeveloperInfo, name='show_DeveloperInfo'),
    path("<id>/", views.scan_img_from_DB),
]

generator/models.py
from django.db import models
from accounts.models import *

class problem(models.Model):
    problem_id = models.CharField(primary_key=True, max_length=13)
    ID = models.ForeignKey(monitor, on_delete=models.CASCADE)
    answer = models.IntegerField()
    type = models.CharField(max_length=20)
    blank_num = models.IntegerField()
    info = models.CharField(max_length=30, null=True)
    image = models.ImageField(upload_to='problems/',null=True, blank=True)
    text = models.TextField(blank=True, null=True)
    blank_text = models.TextField(blank=True, null=True)
    translation_text = models.TextField(blank=True, null=True)
    problem_image = models.ImageField(upload_to='results/', null=True, blank=True)
    keyword_duplicate = models.BooleanField(default=True)

class class_cnt(models.Model):
    class_cnt_id = models.IntegerField(primary_key=True, default=1)
    problem_cnt = models.BigIntegerField(default=1)

generator/forms.py
from django import forms
from .models import problem

class ImageForm(forms.ModelForm):
    class Meta:
        model = problem
        fields = ('image',)

generator/views.py
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from PIL import Image
import pytesseract

from generator.models import *
from generator.refine_text import *
from django.shortcuts import render, get_object_or_404, redirect
from accounts.models import monitor
from .PK_From_DB import *
from .make_blank import Create_Blank
from .make_image import *
from googletrans import Translator
from .forms import ImageForm
import EVM.settings
pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'
def home(request):
    _email = request.session.get('user')
    problem_num = problem.objects.filter(ID=_email).count()
    context = {'email': _email, 'PN': problem_num}
    return render(request, 'generator/Dashboard.html', context)

#사진 업로드 하는 창 부름
def Upload_Photo(request):
    _email = request.session.get('user')
    problem_num = problem.objects.filter(ID=_email).count()

    context = {'email': _email, 'PN': problem_num}

    return render(request, 'generator/Upload_Photo.html', context)

#업로드 된 문제에 관한 정보들을 갖고, problem DB에 저장. 그리고 scan_from_DB로 OCR 인식.
def create(request):
    if(request.method == 'POST'):
        _problem_id = GET_PK("problem")
        _problem_type = request.POST['problem_type']
        _blank_num = int(request.POST['blank_num'])
        _answer = int(request.POST['answer'])
        _info = request.POST['info']
        _keyword_duplicate = request.POST['keyword_duplicate']
        if _keyword_duplicate == 'True':
            _keyword_duplicate = True
        else:
            _keyword_duplicate = False
        _email = request.session.get('user')
        _user = monitor.objects.get(email=_email)

        for img in request.FILES.getlist('imgs'):
            _imgs = img

        _problem = problem(problem_id = _problem_id,ID=_user,type=_problem_type, image=_imgs,
                           blank_num=_blank_num, answer=_answer, info=_info, keyword_duplicate=_keyword_duplicate).save()
        context = scan_img_from_DB(_problem_id)
        context['email']=_email
        context['id']=_problem_id

        request.session['problem_id'] = _problem_id

        return render(request, 'generator/OCR.html', context)
    else:
        return render(request, 'generator/Upload_Photo.html')

#업로드된 문제를 필요에 따라 이미지 자르기.
def beforeImageCrop(request):
    _email = request.session.get('user')
    problem_num = problem.objects.filter(ID=_email).count()
    _problem_id = request.session.get('problem_id')
    _problem = problem.objects.get(problem_id=_problem_id)
    _example = problem.objects.get(problem_id="000000000001")

    context = {'email': _email, 'PN': problem_num, 'problem': _problem, 'example': _example}

    return render(request, 'generator/ImageCrop.html', context)

def ImageCrop(request, word):
    _email = request.session.get('user')
    _problem = problem.objects.get(problem_id=word)

    context = {'email': _email, 'problem': _problem}

    return render(request, 'generator/OneImageCrop.html', context)

#크롭된 이미지에 관한 내용 problem DB에 저장. 그리고 scan_from_DB로 OCR 인식.
def createCropImage(request):
    if(request.method == 'POST'):
        _email = request.session.get('user')
        _problem_id = request.session.get('problem_id')
        _problem = problem.objects.get(problem_id=_problem_id)

        x = float(request.POST.get('x',''))
        y = float(request.POST.get('y', ''))
        width = float(request.POST.get('width', ''))
        height = float(request.POST.get('height', ''))

        print(x, y, width, height)

        croppedImage = crop_image(x, y, width, height, _problem)

        _img_name = "\\problems\\" + _problem_id + "_crop.png"
        _img_path = EVM.settings.MEDIA_ROOT + _img_name

        croppedImage.save(_img_path)

        _problem.image = _img_path
        _problem.save()

        #context = scan_img_from_DB(_problem_id)
        #context['email']=_email
        #context['id']=_problem_id
        return HttpResponse("Succesfully saved to DB!")
    else:
        return render(request, 'generator/Upload_Photo.html')

def crop_to_OCR(request):
    _email = request.session.get('user')
    _problem_id = request.session.get('problem_id')
    _problem = problem.objects.get(problem_id=_problem_id)
    context = scan_img_from_DB(_problem_id)
    context['email'] = _email
    context['id'] = _problem_id
    return render(request, 'generator/OCR.html', context)

def show_problem(request):
    _email = request.session.get('user')
    context = {}
    context['email'] = _email

    _text = request.POST.get('text', '')
    _problem_id = request.session.get('problem_id','')

    _update_prob = problem.objects.get(problem_id=_problem_id)

    _info = _update_prob.info

    # 빈칸 생성.
    _problem_text = Create_Blank(_text, _update_prob.blank_num, _update_prob.keyword_duplicate)

    _img = make_image(_problem_text, _info)

    _img_name = "\\results\\"+_problem_id+"_blank.png"
    _img_path = EVM.settings.MEDIA_ROOT + _img_name

    _img.save(_img_path)

    _update_prob.problem_image = _img_path
    _update_prob.text = _text
    _update_prob.blank_text = _problem_text

    translator = Translator()
    translated_text = translator.translate(_text, dest='ko', src='en').text
    _update_prob.translation_text = translated_text
    _update_prob.save()

    context['problem'] = _update_prob

    return render(request, 'generator/Show_BlankText.html', context)


#DB에서 해당 problem_id 찾은 후, 해당 problem에서 지문 추출 후, 정제까지 완료. 정제된 지문 앱으로 전달.
def scan_img_from_DB(id):
    temp_problem = problem.objects.get(problem_id=id)
    img = Image.open(temp_problem.image)
    one_text = pytesseract.image_to_string(img, lang='kor+eng')

    refined_text = ""

    #유형에 따른 지문 정제
    if(temp_problem.type=="order"):
        refined_text = type_order(one_text, temp_problem.answer)
    elif(temp_problem.type=="blank"):
        refined_text = type_blank(one_text, temp_problem.answer)
    elif (temp_problem.type == "insert"):
        refined_text = type_insert(one_text, temp_problem.answer)
    elif (temp_problem.type == "subject"):
        refined_text = type_subject(one_text)

    temp_problem.text = refined_text
    temp_problem.save()

    context = {'problem':temp_problem}
    return context

# 사용자가 생성한 problem들 보여주기.
def show_UserProblem(request):
    _email = request.session.get('user')
    context = {}
    context['email'] = _email

    candidates = problem.objects.filter(ID=_email)
    context['candidates'] = candidates

    return render(request, 'generator/Show_UserProblemList.html', context)


# 사용자가 생성한 problem 1개 보여주기.
def show_OneProblem(request, word):
    _email = request.session.get('user')
    context = {}
    context['email'] = _email

    candidates = problem.objects.get(problem_id=word)
    context['candidates'] = candidates

    return render(request, 'generator/OneProblem.html', context)

# 사용자가 생성한 problem 1개 보여주기.
def solve_Problem(request, word):
    _email = request.session.get('user')
    context = {}
    context['email'] = _email

    request.session['problem_id'] = word
    candidates = problem.objects.get(problem_id=word)
    context['problem'] = candidates

    return render(request, 'generator/solveProblem.html', context)

# 사용자가 생성한 problem 1개 보여주기.
def show_Answer(request):
    _email = request.session.get('user')
    context = {}
    context['email'] = _email
    _problem_id = request.session.get('problem_id','')

    _problem = problem.objects.get(problem_id=_problem_id)
    context['candidates'] = _problem

    _answerText = _problem.text
    _userSolvedText = request.POST.get('text','')
    _blankText = _problem.blank_text
    _blankCnt = _blankText.count('__________')

    blank_index = 0
    answer_index = 0
    user_index = 0
    cnt_to_next_blank = 0
    useranswerlength = 0
    firstFlag = True
    answer = ""
    userAnswer = ""
    wrongList = []
    allAnswerRight = True
    while blank_index < len(_blankText):
        if _blankText[blank_index] == '_':
            if _blankText[blank_index + 1] == '_':
                useranswerlength = 0
                answer = ""
                userAnswer = ""
                if firstFlag:
                    firstFlag = False
                    answer_index = blank_index
                    user_index = blank_index
                else:
                    answer_index += cnt_to_next_blank
                    user_index += cnt_to_next_blank
                    cnt_to_next_blank = 0

                while _answerText[answer_index] != ' ':
                    answer += _answerText[answer_index]
                    if answer_index < len(_answerText) - 1:
                        answer_index += 1
                    else:
                        break

                while _userSolvedText[user_index] != ' ':
                    userAnswer += _userSolvedText[user_index]
                    useranswerlength += 1
                    if user_index < len(_userSolvedText) - 1:
                        user_index += 1
                    else:
                        break

                if answer != userAnswer:
                    wrongList.append(user_index)
                    wrongList.append(useranswerlength)
                    allAnswerRight = False

                while _blankText[blank_index] != ' ':
                    if blank_index < len(_blankText) - 1:
                        blank_index += 1
                    else:
                        break
        else:
            if firstFlag == False:
                cnt_to_next_blank += 1
            blank_index += 1

    listIndex = 0
    dictText = []
    parseFirst = True
    lastIndex = 0
    while listIndex < len(wrongList):
        index = wrongList[listIndex]
        wronglength = wrongList[listIndex + 1]
        index -= wronglength
        if parseFirst:
            dict = {}
            dict['black'] = _userSolvedText[:index - 1]
            dict['red'] = _userSolvedText[index:index + wronglength]

generator/templates/generator/Dashboard.html
{% extends 'generator/layout.html' %}
{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}"/>
{% endblock %}

{% block content %}
    <!-- header -->
    <header class="header_admin" id="header">
        <div class="top_header">
            <h1 class="logo"><a href="{% url 'generator:home' %}"><img src="{% static 'images/logo.png' %}" alt="EVM"></a></h1>
        </div>
        <nav>
            <ul class="gnb">
                <li>
                    <a href="{% url 'generator:Upload_Photo' %}">문제 생성</a>
                    <br><br>
                    <a href="{% url 'generator:show_UserProblem' %}">생성한 문제 확인 및 풀기</a>
                     <br><br>
                    <a href="{% url 'generator:show_UserBlankNum' %}">빈칸 개수 수정</a>
                     <br><br>
                    <a href="{% url 'generator:show_DeveloperInfo' %}">개발자 정보</a>
                     <br><br>
                </li>
            </ul>
        </nav>
        <style>
        body{background-image: url('https://i.ibb.co/N2btZq6/background.png');
             background-repeat:no-repeat;
            background-position:1%1% ;
            background-attachment: fixed;
            background-size:126%126%;
        }
        </style>
    </header>
    <!-- //header -->

    <!-- main page part -->
    <!-- 첫화면인데.. 문제수 세는방법..-->
    <main id="container">
        <section class="page_admin">
            <div class="tit">
                <div class="member_info_wrap">
                    <button type="button" class="member_info">
                       <strong>{{ email}}</strong>
                    </button>
                    <ul class="list_member_menu">
                        <li><a href="#">My Profile</a></li>
                        <li><a href="#">Change Password</a></li>
                        <li><a href="#">Sign Out</a></li>
                    </ul>
                </div>
            </div>
             <div class="dashboard">
                <div class="card-deck d-flex">
                    <div class="card bg-light mb-3" style="max-width: 25rem;">
                        <div class="card-header">생성한 문제 수 </div>
                        <div class="card-body">
                            <h5 class="card-title"></h5>
                            <p class="card-text">
                                {{ PN }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>


{% endblock %}

generator/templates/generator/OCR.html
{% extends 'generator/layout.html' %}
{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}"/>
{% endblock %}

{% block content %}
    <style>
        .blue_ktn{
            background-color: #B4B4B4;
            color: #ffffff;
            width: 300px;
            height: 70px;
            border: none;
            margin-top:2px;
            cursor: pointer;

        }
    </style>
    <!-- header -->
    <header class="header_admin" id="header">
        <div class="top_header">
            <h1 class="logo"><a href="{% url 'generator:home' %}"><img src="{% static 'images/logo.png' %}" alt="EVM"></a></h1>
        </div>
        <nav>
            <ul class="gnb">
                <li>
                    <a href="{% url 'generator:Upload_Photo' %}">문제 생성</a>
                    <br><br>
                    <a href="{% url 'generator:show_UserProblem' %}">생성한 문제 확인 및 풀기</a>
                     <br><br>
                    <a href="{% url 'generator:show_UserBlankNum' %}">빈칸 개수 수정</a>
                     <br><br>
                    <a href="{% url 'generator:show_DeveloperInfo' %}">개발자 정보</a>
                     <br><br>
                </li>
            </ul>
        </nav>
        <style>
        body{background-image: url('https://i.ibb.co/N2btZq6/background.png');
             background-repeat:no-repeat;
            background-position:1%1% ;
            background-attachment: fixed;
            background-size:126%126%;
        }
        </style>
    </header>
    <!-- //header -->
    <style>
        .left-box {
            float: right;
            margin-right: -50px;
            width: 50%;

        }
        .right-box {

 position:fixed;
            width: 50%;
        }
        .blue_btn{
            background-color: #B4B4B4;
            color: #ffffff;
            width: 310px;
            height: 35px;
            border: none;
            margin-top: 5px;
            cursor: pointer;
        }
        .title_font{
            font-family: 'Limelight', cursive;
            font-size: 1.3em;

        }

    </style>
    <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet">

    <!-- main page part -->
    <main id="container">
        <section class="page_admin">
            <div class="tit">
                <div class="member_info_wrap">
                    <button type="button" class="member_info">
                       <strong>{{email}}</strong>
                    </button>
                    <ul class="list_member_menu">
                        <li><a href="#">My Profile</a></li>
                        <li><a href="#">Change Password</a></li>
                        <li><a href="#">Sign Out</a></li>
                    </ul>
                </div>
            </div>
            <div class="left-box"

                    ><br><font size="5em"  face="나눔고딕">
            [ 문제 사진 ]</font> <br><br><br>
                <img src="{{ problem.image.url}}" alt = "ProblemImage" width="650"
                style="position:relative;">
                <br><br>

                <button onclick = "location.href='/generator/beforeImageCrop/'" class="blue_ktn" style="    margin-left: 180px;">
                    OCR 인식이 정확하지 않나요? <br>
                    여기를 클릭하여 이미지를 잘라주세요!
                </button>
            </div>
            <div class="right-box title_font"
            style=" font-weight:bold;

                    font-style:oblique;">
                <br>



                    </div>
                <br>
            <font size="5em" face="나눔고딕">
            [ OCR 인식 지문 ]</font><br>
                * OCR 인식이 정확하지 않으니 틀린 부분은 수정하세요.<br><br>
                <head>
                    <meta charset="utf-8">
                    <title>HTML</title>
                    <style>
                        /*
                    * {
                        font-size: 20px;
                        font-family: Consolas, sans-serif;
                    }*/
                    textarea {
                        width: 80%;
                        height: 300px;
                    }
                    </style>
                </head>
                <body>
                <form method="POST" action="{% url 'generator:show_problem' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p><textarea name="text" spellcheck="true"
                    style="resize:none;width:650px">
                            {{problem.text}}
                        </textarea>
                    </p>
                    <br>
                    <p>

                        <!-- style="resize:none;float:right;left:-45%;position:relative;height:10%; width:20%;킵-->
                        <div style="'width:80px;right:100px;">
                        <input type="submit" value="Submit" class="blue_btn" style="    margin-left: 180px;">
                    </div>

                    </p>
                </form>
                </body>
            </div>
        </section>
    </main>


{% endblock %}

generator/templates/generator/OneProblem.html
<!DOCTYPE html>
<html lang="en">

    <meta charset="UTF-8">
    <title>문제</title> <br><br>

    <font size="4pm" face="나눔고딕">
    <b>문제 정보 : </b>
    <span>{{ candidates.info }}</span></font>
    <br><br><br><br>

    <font size="4pm" face="나눔고딕">
    <b>문제 사진</b></font><br>
    <img src="{{ candidates.problem_image.url}}" alt = "ProblemImage" width="600">
    <br><br>
    <font size="3pm" face="나눔고딕">
    <b>번역</b>
    <span>{{ candidates.translation_text }}</span></font>
</head>
<body>

</body>
</html>

generator/templates/generator/Show_BlankText.html
{% extends 'generator/layout.html' %}
{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}"/>
{% endblock %}

{% block content %}
    <!-- header -->
    <header class="header_admin" id="header">
        <div class="top_header">
            <h1 class="logo"><a href="{% url 'generator:home' %}"><img src="{% static 'images/logo.png' %}" alt="EVM"></a></h1>
        </div>
        <nav>
            <ul class="gnb">
                <li>
                    <a href="{% url 'generator:Upload_Photo' %}">문제 생성</a>
                    <br><br>
                    <a href="{% url 'generator:show_UserProblem' %}">생성한 문제 확인 및 풀기</a>
                     <br><br>
                    <a href="{% url 'generator:show_UserBlankNum' %}">빈칸 개수 수정</a>
                     <br><br>
                    <a href="{% url 'generator:show_DeveloperInfo' %}">개발자 정보</a>
                     <br><br>
                </li>
            </ul>
        </nav>
    </header>
    <!-- //header -->
    <style>
        .left-box {
            margin-left: 50px;
            width: 100%;
        }

        .title_font{
            font-family: 'Limelight', cursive;
            font-size: 1.3em;
        }

    </style>
    <style>
        body{background-image: url('https://i.ibb.co/N2btZq6/background.png');
             background-repeat:no-repeat;
            background-position:1%1% ;
            background-attachment: fixed;
            background-size:126%126%;
        }
    </style>
    <link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet">


    <!-- main page part -->
    <main id="container">
        <section class="page_admin">
            <div class="tit">
                <div class="member_info_wrap">
                    <button type="button" class="member_info">
                       <strong>{{email}}</strong>
                    </button>
                    <ul class="list_member_menu">
                        <li><a href="#">My Profile</a></li>
                        <li><a href="#">Change Password</a></li>
                        <li><a href="#">Sign Out</a></li>
                    </ul>
                </div>
            </div>
            <br><br><br>
            <div class="left-box">
                <body>
                 <style>

                    textarea {
                        width: 48%;
                        height: 500px;
                    }
                    </style>
                <form method="POST" action="{% url 'generator:create' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <font size="5m" face="나눔고딕">
                        [ 문제 사진 ]</font> <br>
                        * 마우스 오른쪽 버튼으로 문제를 저장하세요.<br><!--원래는 640 && 600-->
                        <img src="{{ problem.problem_image.url}}" alt = "ProblemImage" width="640" style="border:1px solid #b4b4b4">
                        <br><br>
                    </div>
                    <p>
                        <textarea name="text" spellcheck="true" style="position: absolute;left: 1100px;top: 185px;width: 600px;border: 1px solid #b4b4b4;height: 400px;">
                            {{problem.blank_text}}
                        </textarea></p>
                        <br><br>
                </form>
                </body>
            </div>
        </section>
    </main>
{% endblock %}

generator/templates/generator/Upload_Photo.html
{% extends 'generator/layout.html' %}
{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}"/>
{% endblock %}

{% block content %}
    <!-- header -->
    <header class="header_admin" id="header">
        <div class="top_header">
            <h1 class="logo"><a href="{% url 'generator:home' %}"><img src="{% static 'images/logo.png' %}" alt="EVM"></a></h1>
        </div>
        <nav>
            <ul class="gnb">
                <li>
                    <a href="{% url 'generator:Upload_Photo' %}">문제 생성</a>
                    <br><br>
                    <a href="{% url 'generator:show_UserProblem' %}">생성한 문제 확인 및 풀기</a>
                     <br><br>
                    <a href="{% url 'generator:show_UserBlankNum' %}">빈칸 개수 수정</a>
                     <br><br>
                    <a href="{% url 'generator:show_DeveloperInfo' %}">개발자 정보</a>
                     <br><br>
                </li>
            </ul>
        </nav>
    <style>
        body{background-image: url('https://i.ibb.co/N2btZq6/background.png');
             background-repeat:no-repeat;
            background-position:1%1% ;
            background-attachment: fixed;
            background-size:126%126%;
        }
    </style>
    </header>
    <!-- //header -->
    <style>
        .left-box {
            margin-left: 50px;
            width: 100%;
        }
        .input_st{
            display: block;
            width: 340px;
            background-color: transparent;
            -webkit-appearance: none;
            border: solid 1px #CED4DA;
            padding: 5px;
            margin: 1.6rem 0;
            font-size: 1.3rem;
            border-radius: 3px;
            float: right;
            margin-right: 20px;
            margin-top: 0px;
            margin-bottom: 0px;
        }
        .input_tx{
            display: inline-block;
            line-height: 50px;
        }
        .input_bx{
            margin-bottom: 26px;
        }
        .title_style{
            font-family: 'Limelight', cursive;
            margin-bottom: 20px;
            font-size: 4em;
        }
        .blue_btn{
            background-color: #B4B4B4;
            color: #ffffff;
            width: 310px;
            height: 35px;
            border: none;
            margin-top: 5px;
            cursor: pointer;
        }
        .gr_selet{
            width: 300px;
            display: block;
            width: 340px;
            background-color: transparent;
            -webkit-appearance: none;
            border: solid 1px #B4B4B4;
            padding: 5px;
            margin: 1.6rem 0;
            font-size: 1.3rem;
            border-radius: 3px;
            float: right;
            margin-right: 20px;
            margin-top: 0px;
            margin-bottom: 0px;
            height: 45px;

        }
    </style>
<link href="https://fonts.googleapis.com/css2?family=Limelight&display=swap" rel="stylesheet">

    <!-- main page part -->
    <main id="container">
        <section class="page_admin">
            <div class="tit">
                <div class="member_info_wrap">
                    <button type="button" class="member_info">
                       <strong>{{email}}</strong>
                    </button>
                    <ul class="list_member_menu">
                        <li><a href="#">My Profile</a></li>
                        <li><a href="#">Change Password</a></li>
                        <li><a href="#">Sign Out</a></li>
                    </ul>
                </div>
            </div>
            <br><br><br>
            <div class="left-box" style="width: 40%;">
                <p class="title_style">
                    Image Upload
                </p>
                <body>
                <form method="POST" action="{% url 'generator:create' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input_bx">
                        <span class="input_tx">문제 유형</span>
                        <select name="problem_type" class="gr_selet">
                            <option value="order">순서</option>
                            <option value="blank">빈칸</option>
                            <option value="insert">삽입</option>
                            <option value="subject">주제/요지</option>
                        </select>
                    </div>
                    <div class="input_bx">
                        <span class="input_tx">이미지 업로드</span>
                        <input type="file" name="imgs" class="input_st">
                    </div>
                    <div class="input_bx">
                        <span class="input_tx" >정답 번호</span>
                        <input type="text" placeholder = "1~5 사이의 숫자를 입력하세요." class="input_st" name="answer">
                    </div>
                    <div class="input_bx">
                        <span class="input_tx">원하는 빈칸 수</span>
                        <input type="text" placeholder="1~10 사이의 숫자를 입력하세요." class="input_st" name="blank_num">
                    </div>
                    <div class="input_bx">
                        <span class="input_tx">문제 정보</span>
                        <input type="text" placeholder = "EX) 2021 수능특강 빈칸유형 1번" class="input_st" name="info">
                    </div>
                    <div class="input_bx">
                        <span class="input_tx">키워드 여러 번 등장 시 다중 빈칸 생성 여부</span>
                        <input type="hidden" name="keyword_duplicate" value="False" />
                        <label><input type="checkbox" name="keyword_duplicate" value = "True"></label>
                    </div>
                    <input type="submit" value="Upload" class="blue_btn" style="margin-left: 105px">
                </form>
                </body>
            </div>
        </section>
    </main>
{% endblock %}

generator/templates/generator/solveProblem.html
<!DOCTYPE html>
<html lang="en">
    <style>
        .blue_btn{
            background-color: #B4B4B4;
            color: #ffffff;
            width: 200px;
            height: 50px;
            border: none;
            margin-top:2px;
            cursor: pointer;

        }
    </style>
    <form method="POST" action="{% url 'generator:showAnswer' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <meta charset="UTF-8">
        <title>문제</title> <br><br>

        <font size="4pm" face="나눔고딕">
        <b>문제 정보 : </b>
        <span>{{ problem.info }}</span></font>
        <br><br><br><br>
        <font size="4pm" face="나눔고딕">
            <b>문제</b></font>
            <br>
            <font size="3pm" face="나눔고딕">
            ※처음 공백들을 지우고 문제를 풀어주세요.
            </font>
        <p>
            <textarea name="text" style="width: 600px; height: 400px;">
                            {{problem.blank_text}}
            </textarea></p>
        <br><br>
        <input type="submit" value="Submit" class="blue_btn" style="    margin-left: 180px;">
    </form>
</head>
<body>

</body>
</html>