EVM/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('accounts.urls')),
    path('generator/', include('generator.urls')),
    path('admin/', admin.site.urls),
    #url(r'^image/', include('generator.urls')),
              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

accounts/urls.py
from django.urls import path
from .import views

app_name = 'accounts'

urlpatterns=[
    # main menu
    path('', views.login),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name='logout'),
]

accounts/models.py
from django.db import models

# Create your models here.
#model for login
class monitor(models.Model):
    email = models.CharField(primary_key=True, max_length=30)
    fullname = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import monitor
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class LoginForm(forms.ModelForm):
    class Meta:
        model = monitor
        fields = ["email", "password"]

class SignupForm(forms.ModelForm):
    class Meta:
        model = monitor
        fields = ["email", "fullname", "password"]

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import logout as django_logout
from .forms import SignupForm, LoginForm
from .models import monitor
from django.views.decorators.csrf import csrf_exempt
from generator.models import class_cnt, problem
from django.contrib.auth.decorators import login_required

import json
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash


@csrf_exempt
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:  # 오류상황
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,  # 로그인 요청하는 페이지로 다시 이동
    })

@csrf_exempt
def login(request):
    # if there is no class_cnt instance, make one instance
    cnt_class = class_cnt.objects.all().count()
    if cnt_class == 0:
        class_cnt().save()


    if request.method == "POST":
        form = LoginForm(request.POST)
        email = request.POST.get('email')
        password = request.POST.get('password')

        if monitor.objects.filter(email=email).exists():
            cur_monitor = monitor.objects.get(email=email)

            if cur_monitor.password == password:
                problem_num = problem.objects.filter(ID=email).count()
                context = {'email':email, 'PN' : problem_num}
                request.session['user']=email

                return render(request, 'generator/Dashboard.html', context)
            else:
                return render(request, 'main/Alarm_Manage.html')

        return render(request, 'accounts/login_fail.html')

    else:
        form = LoginForm()
        return render(request, 'accounts/login.html', {"form": form})

@csrf_exempt
def logout(request):
    django_logout(request)
    return redirect("/")

accounts/templates/accounts/layout.html
<!--
    layout for accounts app
-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Homepage</title>
  <!-- CSS only (for bootstrap)-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'accounts/css/layout.css' %}">
  {% block extrahead %}
  {% endblock %}


</head>

<header>

    <style>
        body{background-image: url('https://i.ibb.co/Gtfpk9V/final.png'),url('https://i.ibb.co/N2btZq6/background.png');
             background-repeat:no-repeat;
            background-position:0%70%,1%1% ;

            background-size:29%29%,126%126%;
        }
    </style>
    <center>
    <div class="container" href="#">
        <img src="../../static/accounts/images/logo.png" />

    </div>
    </center>
</header>

<body>
    <main><!-- right는 로그인박스, left는 왼쪽사진 ... 지워버렸음 5/26 솔-->

        <div class="main_wrap">

            <center>
            <div class="main_right">
                {%block content%}
                {%endblock%}
            </div>
                </center>
        </div>

    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper (for bootstrap) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html> 

accounts/templates/accounts/login.html
{%extends 'accounts/layout.html'%}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'accounts/css/form.css' %}" />
{% endblock %}

{%block content%}
<div class="accounts-box">
    <div class="accounts-box-header">
        <h3>EVM Login</h3>
    </div>
    <form class="login_form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_email" class="col-form-label">Email</label> 
            <input type="text" class="form-control" name="email" placeholder="name@domain.com" maxlength="30" required="" id="id_email">
        </div>
        <div class="form-group">
            <label for="id_password" class="col-form-label">Password:</label> 
            <input type="password" class="form-control" name="password" placeholder="**********" maxlength="30" required="" id="id_password">
        </div>
        <input type="submit" value="LOGIN" class="btn btn-secondary" style="margin-top: 8px;">
    </form>
    <div class="accounts-box-footer">
        New user? <a style="color: black;" href="{% url 'accounts:signup' %}">Create Account</a>
        <br>
        <a style="color: black;" href="#">Forget password?</a>
    </div>
</div>
{%endblock%}

accounts/templates/accounts/login_fail.html
login failed!

accounts/templates/accounts/signup.html
{%extends 'accounts/layout.html'%}
{% load static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static 'accounts/css/form.css' %}" />
{% endblock %}

{%block content%}
<div class="accounts-box">
    <div class="accounts-box-header">
        Admin Sign Up
        <br>
    </div>
    <form class="signup-form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_fullname" class="col-form-label">Fullname</label>
            <input type="text" class="form-control" name="fullname" placeholder="eg. Michael Jackson" maxlength="30" required="" id="id_fullname">
        </div>
        <div class="form-group">
            <label for="id_email" class="col-form-label">Email</label> 
            <input type="text" class="form-control" name="email" placeholder="name@domain.com" maxlength="30" required="" id="id_email">
        </div>
        <div class="form-group">
            <label for="id_password" class="col-form-label">Password</label> 
            <input type="password" class="form-control" name="password" placeholder="**********" maxlength="30" required="" id="id_password">
        </div>
        <!-- {{form.as_p}} -->
        <input type="submit" value="SIGN UP" class="btn btn-secondary" style="margin-top: 8px;">
    </form>
    <div class="accounts-box-footer" style="color: black;">
        already have an account? <a href="{% url 'accounts:login' %}"></a>
    </div>
</div>
{%endblock%}